[package]
name = "sql-race"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28.1"
sqlx = { version = "0.8.2", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1.40.0", features = ["full"] }
