[package]
name = "sql-race"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
chrono = "0.4.38"
ratatui = "0.28.1"
sqlx = { version = "0.8.2", features = ["runtime-tokio", "sqlite", "chrono"] }
tokio = { version = "1.40.0", features = ["full"] }
