[package]
name = "sql-race"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.89"
chrono = "0.4.38"
futures = "0.3.31"
ratatui = "0.29.0"
sqlx = { version = "0.8.2", features = ["runtime-tokio", "sqlite", "chrono"] }
tokio = { version = "1.40.0", features = ["full"] }
tokio-util = "0.7.12"
tui-textarea = "0.7.0"
widgetui = "0.7.1"
